#!/usr/bin/env python3
"""Independent implementation of the v2 wire encoding.

Why this exists: reference.txt is only as trustworthy as the code that produced
it. A golden vector generated by the implementation it pins proves determinism,
not correctness -- if the encoder is wrong, the vector is confidently wrong too.

This file was written from the layout DOCUMENTED in identity.go and envelope.go,
not from their control flow, and it reproduces every value in reference.txt
byte-for-byte. Two implementations converging is evidence the spec is
unambiguous enough to reimplement -- which is the property that matters, since a
verifier in another language will have to.

Run:  python3 reference.py            # prints vectors for its own inputs
      python3 reference.py --check    # re-derives reference.txt and compares

Keep in step with reference.txt. If they ever disagree, do not "fix" this file
to match: find out which one is wrong.
"""
import hashlib, struct

IDENTITY_DOMAIN    = b"proof-of-deploy/workload-identity/v2\x00"
ENVELOPE_DOMAIN    = b"proof-of-deploy/attestation/v2\x00"
INCARNATION_DOMAIN = b"proof-of-deploy/incarnation/v2\x00"

def lp(s: str) -> bytes:
    b = s.encode()
    return struct.pack(">I", len(b)) + b

def identity_encode(cluster, api, kind, ns, name) -> bytes:
    return IDENTITY_DOMAIN + lp(cluster) + lp(api) + lp(kind) + lp(ns) + lp(name)

def workload_id(*a) -> bytes:
    return hashlib.sha256(identity_encode(*a)).digest()

def incarnation(uid: str) -> bytes:
    if uid == "":
        return b"\x00" * 32
    return hashlib.sha256(INCARNATION_DOMAIN + uid.encode()).digest()

def signing_preimage(version, ident, uid, config_hash) -> bytes:
    enc = identity_encode(*ident)
    return (ENVELOPE_DOMAIN
            + struct.pack(">H", version)
            + struct.pack(">I", len(enc)) + enc
            + lp(uid)
            + config_hash)

def signing_digest(*a) -> bytes:
    return hashlib.sha256(signing_preimage(*a)).digest()

# The config hash used throughout is the real v1 benign/tampered collision from
# this repo — the hash that demonstrates why v2 exists.
CH = bytes.fromhex("89ab57526b689c52761431af4bc5451933c1947b74e0db262438ad1881c17a77")

BASE = ("prod-eu-1", "apps/v1", "Deployment", "payments", "api")
AMB1 = ("prod-eu-1", "apps/v1", "Deployment", "a/b", "c")
AMB2 = ("prod-eu-1", "apps/v1", "Deployment", "a", "b/c")
UID  = "1f8b4c2e-7a3d-4e5f-9c1b-2d3e4f5a6b7c"

def h(b): return b.hex()

_CHECK = __import__("sys").argv[1:2] == ["--check"]

if not _CHECK: print("workloadID_base        ", h(workload_id(*BASE)))
if not _CHECK: print("workloadID_ambiguous_1 ", h(workload_id(*AMB1)))
if not _CHECK: print("workloadID_ambiguous_2 ", h(workload_id(*AMB2)))
if not _CHECK: print("workloadID_other_cluster", h(workload_id("prod-us-1", "apps/v1", "Deployment", "payments", "api")))
if not _CHECK: print("incarnation_uid        ", h(incarnation(UID)))
if not _CHECK: print("incarnation_empty      ", h(incarnation("")))
if not _CHECK: print("preimage_len_uid       ", len(signing_preimage(2, BASE, UID, CH)))
if not _CHECK: print("digest_uid             ", h(signing_digest(2, BASE, UID, CH)))
if not _CHECK: print("digest_no_uid          ", h(signing_digest(2, BASE, "", CH)))
if not _CHECK: print("digest_ambiguous_1     ", h(signing_digest(2, AMB1, UID, CH)))
if not _CHECK: print("digest_ambiguous_2     ", h(signing_digest(2, AMB2, UID, CH)))
if not _CHECK: print("digest_v1_version_field", h(signing_digest(1, BASE, UID, CH)))
if not _CHECK: print()
if not _CHECK: print("preimage_uid_hex       ", h(signing_preimage(2, BASE, UID, CH)))

# --- reference.txt cross-check -------------------------------------------------
# Inputs below are recovered by DECODING reference.txt, not copied from Go, so a
# mismatch means the encoding disagrees rather than that a constant was mistyped.
if __import__("sys").argv[1:2] == ["--check"]:
    import os, re, sys
    txt = os.path.join(os.path.dirname(os.path.abspath(__file__)), "reference.txt")
    want = dict(re.findall(r"(\S+)\s+(\S+)", open(txt).read()))

    enc = bytes.fromhex(want["identityEncoding"])
    body, fields = enc[len(IDENTITY_DOMAIN):], []
    while body:
        n = struct.unpack(">I", body[:4])[0]
        fields.append(body[4:4 + n].decode()); body = body[4 + n:]

    pre = bytes.fromhex(want["signingPreimage"])
    off = len(ENVELOPE_DOMAIN)
    ver = struct.unpack(">H", pre[off:off + 2])[0]; off += 2
    idlen = struct.unpack(">I", pre[off:off + 4])[0]; off += 4 + idlen
    uidlen = struct.unpack(">I", pre[off:off + 4])[0]; off += 4
    uid = pre[off:off + uidlen].decode(); off += uidlen
    ch = pre[off:]

    got = {
        "identityEncoding": identity_encode(*fields).hex(),
        "workloadID":       workload_id(*fields).hex(),
        "incarnation":      incarnation(uid).hex(),
        "signingPreimage":  signing_preimage(ver, fields, uid, ch).hex(),
        "signingDigest":    signing_digest(ver, fields, uid, ch).hex(),
    }
    bad = [k for k in want if want[k] != got.get(k)]
    for k in want:
        print(("MATCH   " if k not in bad else "MISMATCH") + " " + k)
        if k in bad:
            print(f"   reference.txt: {want[k]}\n   recomputed:    {got.get(k)}")
    sys.exit(1 if bad else 0)
